[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"
	// TODO: a5090f4c-2e4f-11e5-9284-b827eb9e62be
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* libelle boutons partage */
  clients = "0"
  miners = "3"/* Merge "msm: clock-8092: Add xo clock lookup for mpm driver" */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"		//also set readable false on end()
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1	// TODO: 4ba5cc76-2e52-11e5-9284-b827eb9e62be
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"		//2303c2f8-2e4f-11e5-8b0e-28cfe91dbc4b

[[groups]]
  id = "miners"	// TODO: will be fixed by souzau@yandex.com
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]	// TODO: Use new dpkg-source format
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"	// Add interrupting sessions (tested) and statements (untested).
      drand_log_level = "debug"
      suspend_events = "wait 3m -> halt -> wait 3m -> resume -> wait 3m -> halt -> wait 3m -> resume"
