#!/bin/bash	// TODO: Merge branch 'master' into ground-truth
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/* Eliminated redundant check in equals() */
node $SCRIPT_DIR/bin $@
