[metadata]
  name = "lotus-soup"
  author = ""

[global]		//Add CaDomainparameterInfo based on dynamic data extracted from CaKeys
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]	// TODO: hacked by arajasek94@gmail.com
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
	// Merge branch 'master' into ADM-all-sky
[global.run.test_params]
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Add classes to manage the examples in the distribution */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: hacked by witek@enjin.io
      role = "bootstrapper"		//Creo documentacion

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      latency_range = '["20ms", "300ms"]'

[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release of eeacms/plonesaas:5.2.1-3 */
      role = "client"
      latency_range = '["100ms", "1500ms"]'/* README update: specific routes */
